### ISSUE TITLE
#issue1

### ISSUE THREAD

**Issue by mukeshwebs** [niklasdie/DynamicIslandForAndroid#3]
not working after giving the access asked in starting

**Comment by niklasdie** [comment]
Which Smartphone and Android version do you use?

**Comment by mukeshwebs** [comment]
android 12 samsung f22

**Comment by niklasdie** [comment]
Do you tried closing the app via setting because you need to stop the foreground service to stop the app.

**Comment by mukeshwebs** [comment]
yes i tried, and it also not shows any notifcation in that dynamic island.
is dynamic island feature working in this app?

**Comment by niklasdie** [comment]
It is in development and far from finished. So notifications do not work yet.

**Comment by mukeshwebs** [comment]
when it is expected to get implemented..?

**Comment by niklasdie** [comment]
I don't know. I try my best.
